apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: PHP
  name: php
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and run PHP applications with official image.
      iconClass: icon-php
      openshift.io/display-name: PHP 
      sampleRepo: https://github.com/openshift/cakephp-ex.git
      supports: php:5,php
      tags: builder,php
      version: "5"
    from:
      kind: DockerImage
      name: oondeo/php-nginx:5
    name: "5"
    referencePolicy:
      type: Source
  - annotations:
      description: Build and run PHP applications with official image.
      iconClass: icon-php
      openshift.io/display-name: PHP 
      sampleRepo: https://github.com/openshift/cakephp-ex.git
      supports: php:7,php
      tags: builder,php
      version: "7"
    from:
      kind: DockerImage
      name: oondeo/php-nginx:7
    name: "7"
    referencePolicy:
      type: Source     
  - annotations:
      description: Build and run PHP applications with official image only FPM.
      iconClass: icon-php
      openshift.io/display-name: PHP 
      sampleRepo: https://github.com/openshift/cakephp-ex.git
      supports: php:5,php
      tags: builder,php
      version: "5-fpm"
    from:
      kind: DockerImage
      name: oondeo/php:5
    name: "5-fpm"
    referencePolicy:
      type: Source
  - annotations:
      description: Build and run PHP applications with official image only FPM.
      iconClass: icon-php
      openshift.io/display-name: PHP 
      sampleRepo: https://github.com/openshift/cakephp-ex.git
      supports: php:7,php
      tags: builder,php
      version: "7"
    from:
      kind: DockerImage
      name: oondeo/php:7
    name: "7-fpm"
    referencePolicy:
      type: Source  
  - annotations:
      description: Build and run PHP applications with official image only FPM.
      iconClass: icon-php
      openshift.io/display-name: PHP 
      sampleRepo: https://github.com/openshift/cakephp-ex.git
      supports: php:7.1,php
      tags: builder,php
      version: "7.1"
    from:
      kind: DockerImage
      name: oondeo/php-nginx:7.1
    name: "7.1"
    referencePolicy:
      type: Source  
  - annotations:
      description: Build and run PHP applications with official image.
      iconClass: icon-php
      openshift.io/display-name: PHP 
      sampleRepo: https://github.com/openshift/cakephp-ex.git
      supports: php:7,php
      tags: builder,php
      version: "latest"
    from:
      kind: ImageStreamTag
      name: "7"
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source

